### ISSUE TITLE
Porte para Firefox

### ISSUE THREAD

**Issue by sitariom** [pyanderson/roll20_tormenta20_grimoire#1]
Primeiramente, excelente trabalho. Parabéns!

Seria possível, caso tenha disponibilidade, disponibilizar um porte compativel com o Firefox?

Obrigado!

**Comment by pyanderson** [comment]
Obrigado pelo feedback @sitariom!

Tenho planos de portar a extensão para firefox, isto estava em espera por que na minha mesa todo mundo usa chrome, então não era uma prioridade. Vou tentar dar uma atenção nisso na proxima release e volto aqui para te dar um retorno.

**Comment by pyanderson** [comment]
@sitariom consegui fazer porte para  [Firefox](https://addons.mozilla.org/pt-BR/firefox/addon/roll20-grim%C3%B3rio-do-tormenta20/) nesse final de semana, e a app foi publicada hoje, quando puder dá uma olhadinha.

**Comment by sitariom** [comment]
> @sitariom consegui fazer porte para [Firefox](https://addons.mozilla.org/pt-BR/firefox/addon/roll20-grim%C3%B3rio-do-tormenta20/) nesse final de semana, e a app foi publicada hoje, quando puder dá uma olhadinha.

Testei na misa mesa ontem, funcionou perfeitamente. Muito obrigado
