### ISSUE TITLE
Problema com as habilidades e poderes

### ISSUE THREAD

**Issue by Calatino** [pyanderson/roll20_tormenta20_grimoire#10]
Tive problema para inserir algumas habilidades e poderes, como por exemplo: Poderes Concedidos - Habitante do Deserto - Azgher.

**Comment by pyanderson** [comment]
Problema resolvido com a [versão 0.3.0](https://github.com/pyanderson/roll20_tormenta20_grimoire/releases/tag/v0.3.0).
