### ISSUE TITLE
Qual ficha de T20 funciona?

### ISSUE THREAD

**Issue by AaronKannon** [pyanderson/roll20_tormenta20_grimoire#11]
Qual ficha de T20 o plugin funciona, eu tento testar em uma mesa que usa a versão Jogo do Ano e está dando uns erros:
![Erros no console](https://github.com/pyanderson/roll20_tormenta20_grimoire/assets/28866153/4820763a-e2f7-4f2a-885d-18244f317e6c)

**Comment by pyanderson** [comment]
Na versão `Tormenta 20`, não tinha visto que tinha sido lançada a versão do jogo do ano hahahah.
![Captura de tela 2023-11-01 153144](https://github.com/pyanderson/roll20_tormenta20_grimoire/assets/4039538/2cd48359-12cd-4864-906c-f53cf0f1b7d4)

**Comment by pyanderson** [comment]
Vou dar uma olhada nessa nova ficha hoje pra ver a dificuldade para adaptar.

**Comment by pyanderson** [comment]
Fiz um ajuste simples e já está funcionando com a versão Jogo do Ano também, acredito que em alguns minutos a nova versão já deve está disponível pra ser instalada.

**Comment by AaronKannon** [comment]
Muito obrigado :smile:
