### ISSUE TITLE
Barra dos Itens (onde aparece o icon do grimório, músicas, macros etc.)

### ISSUE THREAD

**Issue by Slaycker** [pyanderson/roll20_tormenta20_grimoire#4]
Opa meu bom, então, assim, a barrinha onde tem os macros, músicas, personagens e tudo mais, pra mestre, tá dando pau, ela simplesmente fica pra duas linhas e não volta mais, ai me proíbe de criar macro com o a extensão ativa, filtrar coiso na parte de imagens, etc, mas já na de player é normal pq não tem o icon de imagens pra colocar na mesa :D.

Ó:
![image](https://user-images.githubusercontent.com/106133347/169945662-9d7653cb-fd8d-42d2-8c46-5e6dc58e32a7.png)

Ó²:
![image](https://user-images.githubusercontent.com/106133347/169945710-b5332e7c-5aab-4b02-827a-21128029d01b.png)

Eu uso o Opera GX, mas testei no Chrome e deu a mesma coisa...

**Comment by pyanderson** [comment]
Obrigado pela informação @Slaycker, vou dá uma olhada nisso mais tarde. Aparentemente isso é um problema com a própria estilização do roll20, esse ícone é uma "cópia" dos outros icones e parece que a barra de icones do roll20 não é adaptável com a quebra de linhas.

**Comment by pyanderson** [comment]
@Slaycker subi uma versão nova para corrigir esse problema, já está disponível na chrome web store.

**Comment by Slaycker** [comment]
Assim, pra mim seguiu a mesma coisa, já removi e instalei de novo e nada :(

![image](https://user-images.githubusercontent.com/106133347/170277207-f657bac7-48c4-4667-96fb-8401988bbbb1.png)

**Comment by pyanderson** [comment]
Obrigado. Acredito que o fix seja simples, hoje a noite vou dá uma olhada nisso de novo.

**Comment by pyanderson** [comment]
@Slaycker subi outra versão, baixei o Opera GX aqui e aparentemente está funcionando, talvez a engrenagem caia para a linha seguinte, mas dessa vez não deve ficar aquela faixa branca bloqueando a busca das imagens, se isso acontecer você pode atualizar a aba do navegador que deve funcionar normalmente.

**Comment by Slaycker** [comment]
O normal ficou assim, mas por mim perfeito, os botões que ficavam em baixo ficam funcionais msm assim, mas só puxar um pouquinho pro lado e todos ficam em uma linha só, brigadão ai :D

![image](https://user-images.githubusercontent.com/106133347/170380066-7f9a092f-1514-4d22-bbf1-b7a7617aca28.png)
![image](https://user-images.githubusercontent.com/106133347/170380087-6ea627c2-21b8-4763-8cf2-4b0ac7773320.png)
